package builder

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// PostProcessSourceFiles applies post-processing to source files
// to fix truncation issues from free models.
func PostProcessSourceFiles(projectDir string, files []string, lang string, logFn func(string)) {
	fixedCount := 0
	for _, file := range files {
		content, err := os.ReadFile(file)
		if err != nil {
			continue
		}
		original := string(content)
		var fixed string

		switch lang {
		case "go":
			fixed = PostProcessGoCode(original)
		case "c", "cpp":
			fixed = PostProcessCCode(original)
		case "sh":
			fixed = PostProcessShellScript(original)
		default:
			continue
		}

		if fixed != original {
			if err := os.WriteFile(file, []byte(fixed), 0644); err == nil {
				fixedCount++
				logFn(fmt.Sprintf("    🔧 Post-processed: %s (fixed truncation issues)\n", filepath.Base(file)))
			}
		}
	}
	if fixedCount > 0 {
		logFn(fmt.Sprintf("  ✅ Post-processed %d file(s) to fix truncation issues\n", fixedCount))
	}
}

// PostProcessGoCode fixes common truncation issues in Go code generated by
// free models (laguna-s-2.1-free). The model's tokenizer merges "$数字"
// into single tokens, causing missing values in assignments and comparisons.
//
// This function applies heuristic fixes:
// 1. Empty assignments → fill with sensible defaults
// 2. "float" type → "float64"
// 3. Empty array indices → [0]
// 4. Incomplete expressions → complete them
// 5. Missing imports → add them
// 6. Remove unnecessary cgo blocks
func PostProcessGoCode(code string) string {
	// Remove unnecessary cgo blocks (free model sometimes generates these)
	// Pattern: /* ... */ import "C"
	if strings.Contains(code, `import "C"`) {
		// Remove the cgo comment block and import
		start := strings.Index(code, "/*")
		end := strings.Index(code, "*/")
		if start >= 0 && end > start {
			code = code[:start] + code[end+2:]
		}
		code = strings.Replace(code, "\nimport \"C\"\n", "\n", 1)
		code = strings.Replace(code, `import "C"`, "", 1)
	}

	lines := strings.Split(code, "\n")
	var result []string

	for _, line := range lines {
		processed := fixLine(line)
		result = append(result, processed)
	}

	code = strings.Join(result, "\n")

	// Fix type issues
	code = fixTypes(code)

	// Fix missing imports
	code = fixImports(code)

	// Fix incomplete function calls
	code = fixFunctionCalls(code)

	// Fix non-boolean conditions
	code = fixConditions(code)

	return code
}

// fixLine applies line-level fixes for truncation issues.
func fixLine(line string) string {
	// Remove inline comment for pattern matching
	codePart := line
	if idx := strings.Index(line, "//"); idx > 0 {
		codePart = strings.TrimSpace(line[:idx])
	}

	// Pattern 1: Empty assignment "variable = " at end of line
	// Also handle "variable = // comment" (empty value with comment)
	// Also handle "variable = \n" (empty value at end)
	if strings.HasSuffix(codePart, "= ") || strings.HasSuffix(codePart, "=") ||
		(strings.Contains(codePart, "= ") && strings.HasSuffix(strings.TrimSpace(codePart), "//")) ||
		codePart == strings.TrimRight(codePart, " ") + "=" {
		
		// Extract variable name for context
		varName := ""
		if idx := strings.Index(codePart, "="); idx > 0 {
			varName = strings.TrimSpace(codePart[:idx])
		}
		
		if strings.Contains(varName, "Interval") || strings.Contains(varName, "interval") ||
			strings.Contains(varName, "Count") || strings.Contains(varName, "count") ||
			strings.Contains(varName, "Max") || strings.Contains(varName, "Timeout") ||
			strings.Contains(varName, "Temp") || strings.Contains(varName, "Alert") ||
			strings.Contains(varName, "THRESHOLD") || strings.Contains(varName, "INTERVAL") ||
			strings.Contains(varName, "check") || strings.Contains(varName, "normal") ||
			strings.Contains(varName, "warning") || strings.Contains(varName, "limit") ||
			strings.Contains(varName, "default") || strings.Contains(varName, "Thresh") {
			return line + "0"
		}
		if strings.Contains(varName, "Log") || strings.Contains(varName, "log") ||
			strings.Contains(varName, "Path") || strings.Contains(varName, "path") ||
			strings.Contains(varName, "File") || strings.Contains(varName, "file") ||
			strings.Contains(varName, "Zone") || strings.Contains(varName, "zone") {
			return line + `""`
		}
		if strings.Contains(varName, "running") || strings.Contains(varName, "Running") ||
			strings.Contains(varName, "active") || strings.Contains(varName, "Active") ||
			strings.Contains(varName, "enabled") || strings.Contains(varName, "Enabled") {
			return line + " false"
		}
		return line + "0"
	}

	// Pattern 2: Empty comparison "variable <= " or "variable >= " or "variable > "
	if strings.Contains(codePart, "<= ") && strings.HasSuffix(codePart, "<= ") {
		return line + "0"
	}
	if strings.Contains(codePart, ">= ") && strings.HasSuffix(codePart, ">= ") {
		return line + "0"
	}
	if strings.Contains(codePart, "> ") && strings.HasSuffix(codePart, "> ") {
		return line + "0"
	}
	if strings.Contains(codePart, "== ") && strings.HasSuffix(codePart, "== ") {
		return line + `""`
	}

	// Pattern 3: Empty return
	if codePart == "return " || codePart == "return , " || codePart == "return ," {
		if strings.Contains(codePart, ",") {
			return strings.Replace(line, "return ,", "return 0,", 1)
		}
		return strings.Replace(line, "return ", "return nil", 1)
	}

	// Pattern 4: Incomplete return "return " at end
	if strings.HasSuffix(codePart, "return ") {
		return line + "0"
	}

	// Pattern 5: Empty slice/array
	re := regexp.MustCompile(`(\w+)\[\]`)
	if re.MatchString(codePart) {
		line = re.ReplaceAllString(line, "${1}[0]")
	}

	// Pattern 6: Incomplete slice "len(str)-"
	if strings.Contains(codePart, "len(") && strings.Contains(codePart, ")-") {
		line = strings.Replace(line, ")-", ")-1", 1)
	}

	// Pattern 7: Incomplete division "/ ." or "/ " or "/ ,"
	if strings.Contains(codePart, "/ .") || strings.Contains(codePart, "/.") {
		line = strings.Replace(line, "/ .", "/ 1000.0", 1)
		line = strings.Replace(line, "/.", "/ 1000.0", 1)
	}
	// Handle "/ ," (incomplete divisor followed by comma)
	if strings.Contains(codePart, "/ ,") {
		line = strings.Replace(line, "/ ,", "/ 1000,", 1)
	}

	// Pattern 8: Incomplete "return temp /" → "return temp / 1000"
	if strings.HasSuffix(codePart, "/ ") && !strings.HasSuffix(codePart, "/ ") {
		// This is a division without a divisor
		line = line + "1000"
	}

	// Pattern 9: Missing closing brace in format string
	if strings.Contains(line, "%.f") {
		line = strings.ReplaceAll(line, "%.f", "%.1f")
	}

	// Pattern 10: Incomplete ParseFloat call
	if strings.Contains(codePart, "ParseFloat(") && strings.Contains(codePart, ", )") {
		line = strings.Replace(line, ", )", ", 64)", 1)
	}

	// Pattern 11: Empty channel size
	if strings.Contains(codePart, "make(chan") && strings.Contains(codePart, ", )") {
		line = strings.Replace(line, ", )", ", 1)", 1)
	}

	// Pattern 12: Incomplete "return ," → "return 0,"
	if strings.Contains(codePart, "return ,") {
		line = strings.Replace(line, "return ,", "return 0,", 1)
	}

	// Pattern 13: Incomplete "return ." → "return 0.0"
	if strings.HasSuffix(codePart, "return .") {
		line = line + "0"
	}

	// Pattern 14: Double slash in path "//" → "/"
	if strings.Contains(line, `"/`) && strings.Contains(line, `//"`) {
		line = strings.ReplaceAll(line, "//", "/")
	}

	// Pattern 15: Incomplete string assignment
	if strings.HasSuffix(codePart, `"`) && strings.Contains(codePart, `= "`) {
		// Unclosed string - close it
		line = line + `"`
	}

	return line
}

// fixTypes fixes type-related issues.
func fixTypes(code string) string {
	// Replace standalone "float " with "float64 "
	code = strings.ReplaceAll(code, "float ", "float64 ")
	// Fix "float," (in return type) → "float64,"
	code = strings.ReplaceAll(code, "float,", "float64,")
	// Fix "float)" (in return type) → "float64)"
	code = strings.ReplaceAll(code, "float)", "float64)")
	// Fix any double-replaced float6464
	code = strings.ReplaceAll(code, "float6464", "float64")

	// Fix incomplete strconv.ParseFloat calls
	if strings.Contains(code, "ParseFloat(") {
		re2 := regexp.MustCompile(`ParseFloat\(([^,]+),\s*\)`)
		code = re2.ReplaceAllString(code, "ParseFloat($1, 64)")
	}

	return code
}

// fixImports adds missing imports based on code usage.
func fixImports(code string) string {
	// Check if signal is used but not imported
	needsSignal := strings.Contains(code, "signal.Notify")
	hasSignalImport := strings.Contains(code, `"os/signal"`)

	// Check if syscall is used but not imported
	needsSyscall := strings.Contains(code, "syscall.SIG")
	hasSyscallImport := strings.Contains(code, `"syscall"`)

	// Check if os/exec is unused
	hasExecImport := strings.Contains(code, `"os/exec"`)
	usesExec := strings.Contains(code, "exec.Command")

	// Remove unused os/exec import (with or without tab, with or without newline)
	if hasExecImport && !usesExec {
		// Try different patterns
		if strings.Contains(code, "\t\"os/exec\"\n") {
			code = strings.Replace(code, "\t\"os/exec\"\n", "", 1)
		} else if strings.Contains(code, "\t\"os/exec\"") {
			code = strings.Replace(code, "\t\"os/exec\"", "", 1)
		}
	}

	// Add missing imports at the end of import block (before closing paren)
	if (needsSignal && !hasSignalImport) || (needsSyscall && !hasSyscallImport) {
		// Find the import block
		importStart := strings.Index(code, "import (")
		importEnd := strings.Index(code[importStart:], ")")
		if importStart >= 0 && importEnd >= 0 {
			insertPos := importStart + importEnd

			// Build the import lines to add
			var newImports []string
			if needsSignal && !hasSignalImport {
				newImports = append(newImports, "\t\"os/signal\"")
			}
			if needsSyscall && !hasSyscallImport {
				newImports = append(newImports, "\t\"syscall\"")
			}

			// Insert before closing paren
			importBlock := code[importStart : insertPos+1]
			newImportBlock := strings.Replace(importBlock, ")", strings.Join(newImports, "\n")+"\n)", 1)
			code = code[:importStart] + newImportBlock + code[insertPos+1:]
		}
	}

	return code
}

// fixFunctionCalls fixes incomplete function calls.
func fixFunctionCalls(code string) string {
	// Fix os.OpenFile missing third argument (various forms)
	re1 := regexp.MustCompile(`os\.OpenFile\(([^,]+),\s*([^)]*[^,\s)]),?\s*\)`)
	code = re1.ReplaceAllString(code, "os.OpenFile($1, $2, 0644)")

	// Fix strconv.Atoi missing second argument
	re2 := regexp.MustCompile(`strconv\.Atoi\(([^)]*),?\s*\)`)
	code = re2.ReplaceAllString(code, "strconv.Atoi($1)")

	return code
}

// fixConditions fixes non-boolean conditions.
func fixConditions(code string) string {
	// Fix "for running == true" → "for running" (running is now bool)
	code = strings.ReplaceAll(code, "for running == true", "for running")

	return code
}

// PostProcessShellScript fixes common truncation issues in Shell scripts.
func PostProcessShellScript(script string) string {
	// Fix "$" truncation in variable references
	// "$MODPATH" → "${MODPATH}"
	// But avoid double-bracing "${${MODPATH}}"
	script = strings.ReplaceAll(script, "$MODPATH", "${MODPATH}")
	script = strings.ReplaceAll(script, "${${MODPATH}}", "${MODPATH}")

	// Fix incomplete variable references
	// "$" at end of line → remove or complete
	lines := strings.Split(script, "\n")
	var result []string
	for _, line := range lines {
		if strings.HasSuffix(strings.TrimSpace(line), "$") {
			// Incomplete variable - remove trailing $
			line = strings.TrimRight(line, " ")
			line = strings.TrimSuffix(line, "$")
		}
		result = append(result, line)
	}

	return strings.Join(result, "\n")
}

// PostProcessCCode fixes common truncation issues in C code.
func PostProcessCCode(code string) string {
	lines := strings.Split(code, "\n")
	var result []string

	for _, line := range lines {
		processed := fixCLine(line)
		result = append(result, processed)
	}

	code = strings.Join(result, "\n")

	// Fix incomplete array sizes
	re := regexp.MustCompile(`(\w+)\[(\s*)\]`)
	code = re.ReplaceAllString(code, "${1}[256]")

	// Fix format string issues
	code = strings.ReplaceAll(code, "%.f", "%.1f")

	return code
}

// fixCLine applies line-level fixes for C truncation issues.
func fixCLine(line string) string {
	// Remove inline comment for pattern matching
	codePart := line
	if idx := strings.Index(line, "//"); idx > 0 {
		codePart = strings.TrimSpace(line[:idx])
	}

	// Pattern 1: Empty assignment "type var = ;" or "var = ;"
	if strings.HasSuffix(codePart, "= ;") || strings.HasSuffix(codePart, "=;") {
		// Determine default value based on context
		if strings.Contains(line, "running") || strings.Contains(line, "active") ||
			strings.Contains(line, "enabled") || strings.Contains(line, "flag") ||
			strings.Contains(line, "result") {
			return strings.Replace(line, "= ;", "= 0;", 1)
		}
		if strings.Contains(line, "char") || strings.Contains(line, "string") ||
			strings.Contains(line, "str") || strings.Contains(line, "msg") {
			return strings.Replace(line, "= ;", `= "";`, 1)
		}
		return strings.Replace(line, "= ;", "= 0;", 1)
	}

	// Pattern 2: Empty assignment "var =;" (no space)
	if strings.HasSuffix(codePart, "=;") {
		return strings.Replace(line, "=;", "= 0;", 1)
	}

	// Pattern 3: Empty return "return ;" or "return ;"
	if strings.Contains(codePart, "return ;") {
		return strings.Replace(line, "return ;", "return 0;", 1)
	}
	if strings.HasSuffix(codePart, "return") && !strings.Contains(codePart, "return ") {
		return line + " 0;"
	}

	// Pattern 4: Empty function call "sleep();" → "sleep(60);"
	if strings.Contains(codePart, "sleep();") {
		return strings.Replace(line, "sleep();", "sleep(60);", 1)
	}

	// Pattern 5: Empty printf "printf();" → remove or add format
	if strings.Contains(codePart, "printf();") {
		return strings.Replace(line, "printf();", "printf(\"\\n\");", 1)
	}

	return line
}
